### ISSUE TITLE
RPG ADS Crash

### ISSUE THREAD

**Issue by mfb-fake** [yohjimane/xray-16#10]
**Describe the bug**
When using the RPG, it can crash the game when you ADS only when it's LOADED.

**To Reproduce**
1. Pick up the RPG.
2. Reload it.
3. Hold ADS and it will crash.

**Expected behavior**
It looks like that this crash is consistent and ONLY happens when the RPG is LOADED while aiming.

**BugTrap error report**
[OpenXRay_error_report_240402-103628.zip](https://github.com/yohjimane/xray-16/files/14833867/OpenXRay_error_report_240402-103628.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OpenXRay Gunslinger build version 9185. Hotifx 0.2,

**Comment by yohjimane** [comment]
Fixed with hotfix v0.0.8
