### ISSUE TITLE
Explosion bug while vanilla shaders enabled

### ISSUE THREAD

**Issue by mfb-fake** [yohjimane/xray-16#12]
**Describe the bug**
Only happens in vanilal shader mode. When throwing a grenade, or any other explosive it can trigger the screen to be fullbright and after a second or less, the game will work normal as expected.

**To Reproduce**
1. Use a grenade or any other explosive.
2. Throw it.
3. Wait for it to explode.
4. Once it explodes, the game will be fullbright without any sort of shading.

**Expected behavior**
If done correctly, it just makes the shading of the game full bright and that's all.

**Screenshots**
![Screenshot 2024-04-02 084032](https://github.com/yohjimane/xray-16/assets/94538048/90217829-dedb-44ab-a6ef-3632ad061c92)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OpenXRay Gunslinger build 9185. Hotfix 0.2.

**Comment by tiltedcan** [comment]
Unable to repro this on most recent hotfix 12 at least in zaton (map may be a factor? pure conjecture), safe to close for now
