### ISSUE TITLE
Wild flickering

### ISSUE THREAD

**Issue by donizettilorenzo** [yohjimane/xray-16#13]
HF 3 installed

Wild flickering (since the intro videos, window/compositing problem?)
No matter if windowed or fullscreen

**Comment by donizettilorenzo** [comment]
Removed the "SSAO" DLL (AMD or NV SDK?) and there's no more flickering

**Comment by Nomic1** [comment]
I also had this issue, for some reason when I alt-tab and then open the application back up the issue would sometimes resolve itself. A fix was posted a while ago in the discord I had to search find, it's related to the windowed optimizations setting in display-> graphics->default graphics settings->windowed optimization. Turn windowed optimization off and relaunch the game.

**Comment by tiltedcan** [comment]
have not run into this issue since early hotfixes, safe to close.
