### ISSUE TITLE
Blur & Lighting 

### ISSUE THREAD

**Issue by Lapenuch** [yohjimane/xray-16#16]
![True Anomaly](https://github.com/yohjimane/xray-16/assets/165780417/98c21273-2990-4a2a-bc7e-431ca42b7316)
**Describe the bug**
There's no illumination, on top of that insane screen blur when you rotate the camera

**To Reproduce**
1. Walk
2. Rotated the camera
3. Existed

**Expected behavior**
I wanted well, a regular lighting without blurring

**Screenshots**
Screenshot shown

**BugTrap error report**
There was not a single mistake 

**Desktop (please complete the following information):**
Windows 11

**Additional context**
You can't see the water, these are all the mistakes that I noticed, maybe not all of them

**Comment by yohjimane** [comment]
This one is under investigation now.

For now, please use one of the Enhanced graphics options under video settings.

**Comment by tiltedcan** [comment]
this issue isn't reproducible on most recent hotfix 12, safe to close for now.
