### ISSUE TITLE
No lighting in Skadovsk, and no flashlight lighting

### ISSUE THREAD

**Issue by Nomic1** [yohjimane/xray-16#20]
**Describe the bug**
When equipping the flashlight it has no lighting and friendly camps such as Skadovsk have no lighting.
**To Reproduce**
1. Equip and try to use the flashlight
2. See flashlight does not work
3. Go to Skadovsk
4. See hardly anything because there is no lighting inside

**Expected behavior**
Flashlight works and lighting in camps works,

**Screenshots**
![Screenshot 2024-04-02 162237](https://github.com/yohjimane/xray-16/assets/120999564/a557fc37-d4bf-4fab-bc17-95d67558ff14)
Lighting in Skadovsk^

![image_2024-04-02_162538534](https://github.com/yohjimane/xray-16/assets/120999564/cd8f0743-9e55-4cea-a39b-c773d067c3d7)
Lighting outside of Skadovsk^
**My settings
![image_2024-04-02_163115451](https://github.com/yohjimane/xray-16/assets/120999564/0e16a6e4-9755-4ac8-a3a4-ab74cf0b08df)

**Desktop (please complete the following information):**
 - OS: [Windows 11]

**Comment by yohjimane** [comment]
This is fixed with latest hotfix v0.0.6
