### ISSUE TITLE
What's with the shadows and fxaa?

### ISSUE THREAD

**Issue by panadolchick** [yohjimane/xray-16#23]
I have a problem with shadows and smoothing. The screenshot shows that the shadows are too dark and the vegetation is not smoothed out.I've set the settings as in the guide.

![clipboard_image_99c514ac045d4f34](https://github.com/yohjimane/xray-16/assets/150247738/704203f1-d4cb-4f19-b74a-cac63a3c72bb)

 - OS: Windows 10 
 - OpenXRay build version e.g. 421

**Comment by tiltedcan** [comment]
this isn't explicitly a bug, the lighting in this mod is a little more dramatic than original gunslinger so the shadows have tended to be a little darker in my experience, bot SMAA and MSAA antialiasing methods are working in this build. To quickly double check that you have them turned on you can open the console in game with the tilde key (the ~` key) and type msaa use autofill to set an option, then type smaa and make sure it's turned on. As for the brightness and lighting, you can adjust your in game brightness and contrast in the settings menu to your liking.
