### ISSUE TITLE
No video on launch?

### ISSUE THREAD

**Issue by bitbyte90** [yohjimane/xray-16#24]
Well, congrats on the alpha first of all!

Followed the installations instructions to the letter, but now when I launch the Gunslinger EXE thing out it's folder, the game seems to launch with audio, but no picture (I can hear the swish from the GSC video) - doesn't seem to matter how long I leave it, it doesn't eventually load or anything.

It's worth saying, I ran the game after downloading the new hands and stuff through that launcher bit and the game launched fine, it wasn't till adding the other various after that that the picture disappeared!

Figured I'd mention it, has me stumped so far. I just hope I'm helping!

Keep up the good work!

**Comment by yohjimane** [comment]
Does alt tabbing back and forth while you can hear the sound help at all?

**Comment by yohjimane** [comment]
And btw, thank you for your kind words :)

**Comment by bitbyte90** [comment]
Nothing - it was just audio - the audio was continually playing through alt-tabs, it still seemed to have all the behaviors of... well, any other program although invisible.

I'm gonna give it another chance in a minute with another fresh install, I would've thought I'd have seen somebody out there with the same issue! If it persists I can see about providing you any other info (if you need it.)

**Comment by tiltedcan** [comment]
Are you still experiencing this issue? And if you are could you attach your logs?

**Comment by bitbyte90** [comment]
Hey there, currently no.

I reinstalled everything the only difference was I didn't click on one of the addons on that launcher (it was the one that had 4 versions to choose from), followed the guide etc, and the game is launching properly, it's even loading into engine and the like, however..

Now I'm left with this horrendous.... flickering on the screen, so I'm going to go look up to see if anyone else is having that issue! 

(And since I did it before I hit post - I just alt+tabbed for two seconds, went in and the issue has gone. xD haha!)
Ach well, all problems are A.Ok just now! I'll post if there's any other issues!

**Comment by tiltedcan** [comment]
the flickering seems to be tied to fullscreen settings and I also saw some people saying that the windowed mode optimization in windows settings can cause problems as well. 
***some ideas to fix:***
1. go to windows settings
2. click system 
3. click display (top of list)
4. click graphics at bottom of list
5. click "change default graphics settings" at top below header "Default settings"
6. toggle "Optimizations for windowed games" to OFF

another thing you might try is changing from windowed mode, restart the game, then change back to fullscreen in OXRGS settings this helped me.

I still get some minor flickering but I haven't figured out if it's a gsync issue or what and my performance has some anomalous behavior, more testing required

**Comment by tiltedcan** [comment]
Issue isn't reproducible on newest hotfix 12, safe to close for now.
