### ISSUE TITLE
Crash to desktop when loading autosave from pause menu

### ISSUE THREAD

**Issue by tiltedcan** [yohjimane/xray-16#25]
**Describe the bug**
CTD when loading autosave from pause menu (this crash happened when loading the autosave for "deal by the ranger station"

**To Reproduce**
1. progress through the game until the game generates an autosave at a given plot progression point
2. Pause the game and load the generated autosave
3. See error - game will crash to desktop

**Expected behavior**
Save will load and you will be brought back to the point in the game where the autosave was generated

**BugTrap error report**
[OpenXRay_error_report_240403-082835.zip](https://github.com/yohjimane/xray-16/files/14854752/OpenXRay_error_report_240403-082835.zip)

**Desktop**
 - OS: Windows 11 (Atlas OS if that's relevant)
 - OpenXRay Gunslinger  v0.0.1 with hotfix  v0.0.9 installed

**Additional context**
I wasn't able to get this to happen consistently, I was only able to get 2/7 attempts for replication, I will note that both the times it happened MAY have been because I loaded the save immediately after killing one of my fellow stalkers and failing the quest I was on. Normally I wouldn't make a bug report without a more consistent replication method but, I can submit this with a crash log and I thought it may be useful. I encourage feedback from the devs so I can shape my testing and bug submission methodology to best suit the most pressing matters.

**Comment by yohjimane** [comment]
This might be addressed with hotfix v0.0.9 - can you install it and try to repro and let me know how it goes? Thank you!

**Comment by tiltedcan** [comment]
I had  v0.0.9 installed for the initial issue submission and just tested it with  v0.0.9.1 and it was more reproducible than before 7/7 attempts I was able to get CTD
Here's an updated report
[OpenXRay_error_report_240403-181222.zip](https://github.com/yohjimane/xray-16/files/14860138/OpenXRay_error_report_240403-181222.zip)

**Comment by yohjimane** [comment]
Dangit, This may be a separate issue then.. If you start a new game and wait for the initial new game autosave to happen, then load last save, does it still reproduce?

**Comment by tiltedcan** [comment]
So, I was going to try to go back to skadovsk to investigate issue #30 further and I would reliably get CTD when trying to travel even with the jump command. I tried deleting more recent autosaves, but every time it would crash. Then I went to sleep for 8 hours and was able to travel and load autosaves successfully I have boat load of reports if they're useful. I did start a new game and then load the autosave just in case and it worked that time as well.

**Comment by tiltedcan** [comment]
Just in case because I'm going to be heading out here in a sec. 
here is the most recent error report 
[OpenXRay_error_report_240403-183548.zip](https://github.com/yohjimane/xray-16/files/14860335/OpenXRay_error_report_240403-183548.zip)
and here is the most recent log from when it worked just fine
[logs.zip](https://github.com/yohjimane/xray-16/files/14860346/logs.zip)
maybe the difference between the two will shed some light on things

**Comment by tiltedcan** [comment]
I am unable to reproduce this issue with hotfix 12, closing for now
