### ISSUE TITLE
Nvidia overlay CTD

### ISSUE THREAD

**Issue by RenegadoHS** [yohjimane/xray-16#3]
ALT + R or ALT + Z in-game cause CTD
ALT + R or ALT + Z on menus no CTD, and it works, but if you press ESC to go back to  game it CTD.

Open your game, load a save or start a new game and try to use nvidia overlay (ALT + R or ALT + Z)

**BugTrap error report**
[userdata.zip](https://github.com/yohjimane/xray-16/files/14830676/userdata.zip)

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - OpenXRay build version latest with hotfix 1

**Comment by tiltedcan** [comment]
Hey there, just chiming in here, this issue may be tied to the use of the old geforce experience app vs the new nvidia app for the nvidia overlay. The nvidia app is generally a great upgrade over the old geforce experience and you might want to consider switching over. I have different hardware than you and I'm on windows 11 so take what I say with a grain of salt, but I wasn't getting the ctd when using my nvidia overlay. Also I don't see anything in your logs that points to the game actually failing I.E. there's no stack trace present in your logs. what I do see is that there is an issue with the nvidia ansel dll on your system. I recommend either reinstalling geforce experience or moving to the new nvidia app

**Comment by tiltedcan** [comment]
Was never able to repro this issue and never received more information, this can be safely closed for now
