### ISSUE TITLE
Lighting flicker in skadovsk

### ISSUE THREAD

**Issue by tiltedcan** [yohjimane/xray-16#30]
**Describe the bug**
The light source near Owl in skadovsk produces some odd flickering behavior

**To Reproduce**
1. Boot game and make your way to skadovsk
2. go upstairs to Owl's room and stand near the wall on the right side coming in
3. See error - lighting flicker

**Expected behavior**
Light emission from the light source will remain solid unless obstructed

**Screenshots**

https://github.com/yohjimane/xray-16/assets/12876132/50e1ecdd-55f1-4e99-a102-3d323fa8ad5a

**BugTrap error report**
N/A

**Desktop**
 - OS: Windows 11 (AtlasOS)
 - OpenXRay Gunslinger  v0.0.1 with hotfix  v0.0.9

**Comment by yohjimane** [comment]
IIRC this is a bug with original OXR, it might be due to mt_* settings

**Comment by tiltedcan** [comment]
I don't know what mt_* settings are but this can probably be safely closed and I can open a separate issue report in the base OXR project if that's helpful
