### ISSUE TITLE
CTD when Noah would take the player to the teleporter anomaly

### ISSUE THREAD

**Issue by tiltedcan** [yohjimane/xray-16#31]
**Describe the bug**
When selecting the "Let's go." dialog when Noah offers to lead the player to the plateau teleporter anomaly the game will fade to black and then crash to desktop

**To Reproduce**
1. Progress through the game until you receive the quest "Getting to the plateau: find out how to get there from Noah"
2. Make your way to Noah's cabin and speak to him
3. select dialog option 1.  3 times in a row (the final dialog choice will be "Let's go.")
4. See error - game will reliably crash to desktop

**Expected behavior**
Noah and player will be teleported to the burnt farmstead and a cutscene will play where Noah shows the player how to navigate the burner anomalies and make it to the teleporter anomaly

**Screenshots**
![ss_coleman stoll_04-03-24_17-22-46_(zaton)](https://github.com/yohjimane/xray-16/assets/12876132/d99bec0e-b5fa-4489-a445-e8c6eb3218b1)
![ss_coleman stoll_04-03-24_17-22-49_(zaton)](https://github.com/yohjimane/xray-16/assets/12876132/4294fc7d-b004-436a-8b6c-e1f3c07f3c4d)
![ss_coleman stoll_04-03-24_17-22-52_(zaton)](https://github.com/yohjimane/xray-16/assets/12876132/2bc1c577-58d1-41f3-baa9-6490b9867527)

**BugTrap error report**
[OpenXRay_error_report_240403-172300.zip](https://github.com/yohjimane/xray-16/files/14859862/OpenXRay_error_report_240403-172300.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11 (AtlasOS)
 - OpenXRay Gunslinger v0.0.1 with hotfix  v0.0.9

**Comment by yohjimane** [comment]
This should be fixed with v0.1.0

**Comment by tiltedcan** [comment]
Issue was fixed with hotfix v0.1.0, closing
