### ISSUE TITLE
minor bugs

### ISSUE THREAD

**Issue by xTIMB3Rx** [yohjimane/xray-16#33]
A few minor bugs ive encountered, sometimes when talking to npcs the mouse cursor in game completely disappears and the only way to fix it is to reload prior save. Another is sometimes the sprint button just quits working and major cannot run, this typically happens when i would use a hercules or stalker energy drink.

**Comment by xTIMB3Rx** [comment]
windows 11 
openxray with hotfix

**Comment by tiltedcan** [comment]
Hey there, please only submit bug reports on issues that you've been able to reproduce and follow the bug report template, if you don't have time to make a full report and reproduce an issue DM me on discord (my username is Fux) with some basic information about the issue and I will submit a proper report. Bad data can hurt more than help when the devs are trying to fix issues so it helps a lot to have good clean data. Thanks!

**Comment by yohjimane** [comment]
Closed due to incorrect report format
