### ISSUE TITLE
Crash to desktop when shot at by AI with Wincheaster 1300 shotgun

### ISSUE THREAD

**Issue by tiltedcan** [yohjimane/xray-16#34]
**Describe the bug**
When being shot at by an AI that is using the Wincheaster 1300 shotgun game will reliably crash the game and return to desktop

**To Reproduce** 
(7/7 times tested 100% repro rate) Steps to reproduce the behavior:
1. Start new game and use the console command  "g_god on" to make testing easier 
2. Go to the nearby sawmill 
3. Get shot by hostile AI in sawmill until game crashes
4. See error - when a hostile AI shoots you with a wincheaster 1300 you will hear the shot and the game will crash 

**Expected behavior**
player will take damage from the AI shooting them but game will continue playing

**Screenshots**
N/A - CTD

**BugTrap error report**
[OpenXRay_error_report_240406-012123.zip](https://github.com/yohjimane/xray-16/files/14892970/OpenXRay_error_report_240406-012123.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11 (Atlas OS) 
 - OpenXRay Gunslinger v 0.0.1 with hotfix v0.1.01

`[error] Expression    : <no expression>`
`[error] Function      : CInifile::r_section`
`[error] File          : F:\modding\yohji_gunsl_engine\src\xrCore\xr_ini.cpp`
`[error] Line          : 734`
`[error] Description   : fatal error`
`[error] Arguments     : Can't open section 'wpn_winchester1300_ammo_bones' (only 'wpn_winchester1300_ammo_bones_blue' avail). Please attach [*.ini_log] file to your bug report`

**Additional context**
I have only tested this with the zombie AI at the sawmill but the stack trace points to an issue with the weapon files, not something necessarily to do with AI so it shouldn't matter I don't think.

**Comment by tiltedcan** [comment]
I was able to get this to repro by just standing still in the middle of the sawmill area, but I was able to get through the encounter without a crash by using cover well, so it might be more specifically tied to the player being hit by the shot will do more investigation if requested.

**Comment by yohjimane** [comment]
I have a fix for this that will be included with the next hotfix! I'll let you know when it's ready to test.

**Comment by yohjimane** [comment]
Should be fixed with hotfix v0.1.02

**Comment by tiltedcan** [comment]
looks like this bug is squashed, nice
