### ISSUE TITLE
CTD viewing map

### ISSUE THREAD

**Issue by edmundnoble** [yohjimane/xray-16#4]
**Describe the bug**
Pressing M after starting a new game on Veteran crashes the game. 

So far happens with minimum and maximum graphics settings and with enhanced shaders on and off. 

**To Reproduce**
1. Start new game on Veteran
2. Skip intro cutscene
3. Press m
4. Crash

**BugTrap error report**

[OpenXRay_error_report_240401-222300.zip](https://github.com/yohjimane/xray-16/files/14830754/OpenXRay_error_report_240401-222300.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OpenXRay build version [e.g. 421]

**Additional context**
Pressing P after starting a new game brings up the PDA, until I scroll out on the map and it crashes. The PDA is also definitely the wrong size, it's too large or close to the camera.

**Comment by yohjimane** [comment]
Thank you for the report, prioritizing this one as high priority.

**Comment by yohjimane** [comment]
Fixed with hotfix v0.0.2
