### ISSUE TITLE
Grenade Launchers, Rocket Launcher won't fire

### ISSUE THREAD

**Issue by yohjimane** [yohjimane/xray-16#43]
**Describe the bug**
Inconsistent behavior with mounted UBGLs, GLs and Rocket Launchers

**To Reproduce**
1. Acquire and mount the GL on an AK-74 (presumably more guns but I wouldn't know I haven't tested it yet)

2. Attempt to load a grenade into the GL and try to fire

3. GL clicks indicating it's empty (and HUD shows empty GL)

**Expected behavior**
GL be able to fire when loaded.

**Desktop (please complete the following information):**
On Windows 10, OXR Alpha 1, patch 0.1.08 candidate

**Additional context**
Other heavy weapons also face similar issues, they should be checked out.

**Comment by tiltedcan** [comment]
Fix verified, however when testing this I noticed that the RGM 40 Grenade launcher does not launch the grenade projectiles correctly, all of the UBGLs appear to adjust grenade trajectory based on where the player is aiming when ADS'd RGM 40's range is pretty short and doesn't feel particularly usable such as it is.

**Comment by yohjimane** [comment]
Fixed with commit 4a6973cad2e3d3fbbf84569f64cbb6842f81fd27
