### ISSUE TITLE
Player becomes unable to do some actions after using consumables

### ISSUE THREAD

**Issue by tiltedcan** [yohjimane/xray-16#46]
**Describe the bug**
After using a consumable, the player will be unable to sprint and interact with npcs or containers

**To Reproduce**
1. Start new game
2. Use any consumable
3.  See error - player will be unable to sprint or interact

**Expected behavior**
player will be able to sprint and interact after finishing consumable animation

**Screenshots**

https://github.com/yohjimane/xray-16/assets/12876132/1e4f61af-8546-459b-9bf8-8eb7f4fe1901

**BugTrap error report**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11 (AtlasOS)
 - OpenXRay Gunslinger testing build (I believe it was the build Yohji sent me after commit 14ea7de80375d005824baec8cb41f340f8865a11)

**Additional context**
I didn't test EVERY consumable but I tested with about 10 or so, and every one caused the issue. Conjecture: could be that the using consumable animation state that disables sprinting and interaction just isn't ending?

**Comment by yohjimane** [comment]
Can't repro on latest yohji/dev branch

**Comment by yohjimane** [comment]
Nvm, it works if you have a weapon equipped, but when unarmed I can repro the bug. New fix pushed to yohji/dev!

**Comment by tiltedcan** [comment]
Fix verified on latest yohji/dev branch via commit 5200838fe4b3a418218e11794ae497cb7be21ee5
