### ISSUE TITLE
Reload with only bullet in the chamber will not function correctly

### ISSUE THREAD

**Issue by tiltedcan** [yohjimane/xray-16#48]
**Describe the bug**
Reload will fail when attempted with only a bullet in chamber of currently equipped weapon and no bullets in the magazine

**To Reproduce**
1.  Equip any weapon with more than one round in its magazine
2. Fire rounds until you have no bullets in the magazine and one bullet in the chamber
3. Press R to reload
4. Reload animation will not play and magazine will not be set back to full
**Expected behavior**
Player should be able to reload with any number of bullets in the weapon that is less than the maximum

**Screenshots**
(https://www.youtube.com/watch?v=l0cmgEjZW6Q)

**BugTrap error report**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OpenXRay Gunslinger Alpha v0.0.1 Hotfix hotfix v0.1.11

**Additional context**
This appears to affect every weapon with the exception of single shot weapons and weapons without a magazine, I have not tested every weapon, just a lot of them but it appears to be a global issue in regards to weapons

**Comment by yohjimane** [comment]
fix pending verification on latest yohji/dev branch

**Comment by tiltedcan** [comment]
Fix verified on latest yohji/dev branch via commit 640e201cf1c5444786404f903896dd328f9e30b8
