### ISSUE TITLE
Using a consumable while holding PDA will cause animation loop

### ISSUE THREAD

**Issue by tiltedcan** [yohjimane/xray-16#49]
**Describe the bug**
Using a medkit while holding PDA will cause animation loop, player character will loop the initial putting away pda animation

**To Reproduce**
1. Open PDA 
2. quick use a medkit with whatever key it is assigned to
3. See issue, animation loop occurs

**Expected behavior**
Player character will put away PDA to use the medkit

**Screenshots**
https://www.youtube.com/watch?v=suttcFPmlTA

**BugTrap error report**
N/A

**Desktop (please complete the following information):**
- OS: Windows 11
- OpenXRay Gunslinger Alpha v0.0.1 Hotfix hotfix v0.1.11

**Comment by yohjimane** [comment]
fix pending verification on latest yohji/dev branch
