### ISSUE TITLE
Crashing about 10 seconds after world load.

### ISSUE THREAD

**Issue by 333pier** [yohjimane/xray-16#5]
After opening cutscene, can move and look around for a few second or so and then game crashes.

1. Start a new game
2. Load into an existing save
3. Crash.
EDIT - hotfix applied and got about two/three minutes further then crashed with the same exception= xrCore.dll" at 0033:00007FFCC099844C, xrDebug::Fail()+604 byte(s)

[OpenXRay_error_report_240402-062819.zip](https://github.com/yohjimane/xray-16/files/14832039/OpenXRay_error_report_240402-062819.zip)

 - OS: Windows 10 
 - OpenXRay build version [e.g. 421]

**Comment by yohjimane** [comment]
This seems like it could be an installation issue, since the crash is due to a missing weapon animation file, which I confirmed exists in the current build.

Can you try to reinstall, following this guide https://www.youtube.com/watch?v=G2JKp21NyF4 and let me know how it goes?

**Comment by tiltedcan** [comment]
Never able to repro, and never received more information, can safely be closed for now
