### ISSUE TITLE
Impact Grenades do not explode on impact

### ISSUE THREAD

**Issue by tiltedcan** [yohjimane/xray-16#50]
**Describe the bug**
Neither RGO or RGN impact grenades explode when contacting solid mesh

**To Reproduce**
1. Equip either of the impact grenades
2. Throw equipped grenade
3. See issue - grenade explodes a few seconds after impact

**Expected behavior**
Grenade will explode when contacting solid mesh

**Desktop**
 - OS: Windows 11 (AtlasOS)
 - OpenXRay Gunslinger Alpha v0.0.1 hotfix v0.1.11

**Comment by yohjimane** [comment]
fix pending verification on latest yohji/dev branch, please also check vanilla Gunslinger to make sure logic matches up!

**Comment by tiltedcan** [comment]
Fix is not currently having desired outcome, grenades still explode a few seconds after contact

**Comment by tiltedcan** [comment]
Fix verified on latest yohji/dev branch via commit 8fe6de7b9d311d5d14c2dba9a17e6705f52a298f
