### ISSUE TITLE
Shader Night Vision does not recover from blowout/emission glitching

### ISSUE THREAD

**Issue by tiltedcan** [yohjimane/xray-16#51]
**Describe the bug**
If the player character has Gen 1 NODs active when subject to blowout effects, the distortion and glitch effects do not disappear after the blowout subsides

**To Reproduce**
1. Equip Generation 1 night vision
2. Wait for a blowout to occur
3. activate night vision device
4. wait for blowout to subside
5. See Issue - glitch effects will continue after blowout is over
**Expected behavior**
Glitch effects will go away as the blowout subsides

**Desktop (please complete the following information):**
 - OS: Windows 11 (AtlasOS)
 - OpenXRay Gunslinger Alpha v0.0.1 hotfix v0.1.11

**Comment by yohjimane** [comment]
Fixed, and also added blackout effect for shader nightvision as well - on latest yohji/dev branch

**Comment by tiltedcan** [comment]
Fix verified on latest yohji/dev branch via commit c6c86263604bbbf3e63acb346c8264eecccd1c6d

Editorial: should we mute the nightvision sounds when the blackout occurs? feels a little weird that the audio continues to play when presumably the emission has caused the NVGs to shut off

**Comment by yohjimane** [comment]
Ah good point, i can look into it
