### ISSUE TITLE
Collecting important or quest item when holding weapon or tool will cause PDA to open

### ISSUE THREAD

**Issue by tiltedcan** [yohjimane/xray-16#52]
**Describe the bug**
When holding any weapon or tool that uses the right hand, collecting an important item/quest item will force the PDA to open without user input.

**To Reproduce**
1. Start new game
2. Go to Cardan and accept the quest to find tools
3. go to the Sawmill from the beginning of the game (do not pick up the tools at the start of the game)
4. Before picking up the tools, equip and unholster any weapon or tool that requires use of player characters right hand (any pistol is an easy choice)
5. Pick up the basic toolkit in the attic of the building in the northeastern quadrant of the sawmill complex
6. See Issue - Player character will pull out PDA after the player character picks up the  basic toolkit

**Expected behavior**
PDA will not open without user input

**Desktop**
 - OS: Windows 11 (AtlasOS)
 - OpenXRay Gunslinger Alpha v0.0.1 hotfix v0.1.11

**Comment by yohjimane** [comment]
fix pending verification on latest yohji/dev branch

**Comment by tiltedcan** [comment]
Fix verified on latest yohji/dev branch via commit 187d654d4ebf8b8c4088032c0dff55b798d9d840
