### ISSUE TITLE
PiP/SVP Scopes that do not have zoom adjustment feature will still play animation and sound effect when mouse wheel is scrolled

### ISSUE THREAD

**Issue by tiltedcan** [yohjimane/xray-16#53]
**Describe the bug**
PiP/SVP Scopes that do not have zoom adjustment feature will still play animation and sound effect when mouse wheel is scrolled

**To Reproduce**
1. Acquire any weapon that supports a fixed zoom PiP scope 
2. Equip weapon and corresponding fixed zoom PiP scope
3. Aim
4. Scroll mouse wheel either up or down
5. See Issue - animation and sound for adjusting scope zoom will play

**Expected behavior**
Scopes with fixed zoom will not play this animation and sound when the mouse wheel is scrolled

**Desktop (please complete the following information):**
 - OS: Windows 11 (AtlasOS)
 - OpenXRay Gunslinger Alpha v0.0.1 hotfix v0.1.11

**Comment by yohjimane** [comment]
fix pending verification on latest yohji/dev branch

**Comment by tiltedcan** [comment]
Fix verified with latest yohji/dev branch via commit c49ca66538bb71c1ba0a18a6940d09d9b4462307
