### ISSUE TITLE
AN-94 Hyper burst doesn't function correctly

### ISSUE THREAD

**Issue by tiltedcan** [yohjimane/xray-16#54]
**Describe the bug**
AN-94 Hyper burst feature only fires one shot instead of the expected two shots

**To Reproduce**
1. Equip and unholster AN-94 Abakan
2. cycle fire modes until fire mode indicator says "2"
3. fire weapon
4. See issue - weapon will fire one bullet per click/trigger pull

**Expected behavior**
AN-94 will fire two bullets per click/trigger pull

**Desktop (please complete the following information):**
 - OS: Windows 11 (AtlasOS)
 - OpenXRay Gunslinger Alpha v0.0.1 hotfix v0.1.11

**Comment by yohjimane** [comment]
fix pending verification on latest yohji/dev branch

**Comment by tiltedcan** [comment]
Fix verified on latest yohji/dev branch via commit 55dc02be683ea0eb171a15327ae1a1ef412b4fcd
