### ISSUE TITLE
Crash when closing bear detector 

### ISSUE THREAD

**Issue by nakanaki** [yohjimane/xray-16#6]
**Describe the bug**

**To Reproduce**
1. open bear detector 
2. close bear detector
3. crash

**Expected behavior**
close detector 

**Screenshots**
-

**BugTrap error report**
[OpenXRay_error_report_240402-025610.zip](https://github.com/yohjimane/xray-16/files/14832182/OpenXRay_error_report_240402-025610.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OpenXRay build version 0.0.1 hotfix 0.0.2

**Additional context**
-open detector mapped on X keyword

**Comment by yohjimane** [comment]
Fixed with hotfix v0.0.4
