### ISSUE TITLE
Multiple bug report.

### ISSUE THREAD

**Issue by mfb-fake** [yohjimane/xray-16#7]
**Describe the bug**
First bug: When grenades or explosions explode, they cause the image to go to level editor mode when using vanilla shaders.
Second bug: When picking up ammo or other objects, it's possible to a reload extremely fast or instantly.
Third bug: PiP scopes do not work when vanilla shaders are enabled.
Fourth bug: When picking up items it's possible that the pickup animation will show the item being picked up, but the item itself won't be picked up to your inventory and will stay where it's last position was.
Fifth bug: When using the RPG while it is loaded (not unloaded), it can cause a crash when aiming with ADS, althought i'm not sure if it's a consistent crash.

**To Reproduce**
First bug: Throw any explosive and once they explode in vanilla shader mode, they will cause the first bug.
Second bug: Pick up any dynamic object and try to press the reload key, if done correctly it will instantly reload your gun or other weapons.
Third bug: Enable vanilla shader mode and use any PiP scopes.
Fourth bug: Pick up any item and it may cause this bug.
Fifth bug: Use an RPG and try to ADS with it.

**Expected behavior**
No idea how all of this works, lol.

**Screenshots**
First bug: 
![Screenshot 2024-04-02 084032](https://github.com/yohjimane/xray-16/assets/94538048/09011bf7-23d4-4cf3-978c-4fe56b477214)
Second bug: 
![ammo bug](https://github.com/yohjimane/xray-16/assets/94538048/e7fc31fd-8067-4e89-b731-d9b70ae5b537)
Third bug: 
![Screenshot 2024-04-02 083659](https://github.com/yohjimane/xray-16/assets/94538048/3e132974-1e03-4fa3-8334-5c3eb580a0cc)
Fourth bug: 
![Screenshot 2024-04-02 083044](https://github.com/yohjimane/xray-16/assets/94538048/c446678f-e7c0-4162-96c9-bf2629c05d17)

**BugTrap error report**
For the RPG crash.
[OpenXRay_error_report_240402-082024.zip](https://github.com/yohjimane/xray-16/files/14833123/OpenXRay_error_report_240402-082024.zip)

**Desktop:**
 - OS: Windows 11
 - OpenXRay Gunslinger build version 9185 with hotfix 0.2

**Additional Context:**
All of the other bugs, except the first and the third bug were taken with new shaders support,

**Comment by yohjimane** [comment]
Closed due to improper format (1 bug per ticket, please!)
