### ISSUE TITLE
Reload glitch bug

### ISSUE THREAD

**Issue by mfb-fake** [yohjimane/xray-16#9]
**Describe the bug**
When picking up any item or just ammo itself, it's possible to press the reload key and the weapon you have will reload extremely fast or instantly.

**To Reproduce**
1. Equip any weapon you wish to reload
2. Pick up any item that's on the ground.
3. During the pickup animation, press the reload key and it should reload it extremely fast or instantly.

**Expected behavior**
If done correctly, this will cause your gun to reload stupidly fast or instantly.

**Screenshots**
![Screenshot 2024-04-02 093202](https://github.com/yohjimane/xray-16/assets/94538048/74a8bd5f-2462-4742-998e-8a35b8d03853)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OpenXRay Gunslinger build version 9185. Hotfix 0.2.

**Comment by yohjimane** [comment]
Reload while pickup animation is playing is fixed with hotfix v0.0.4
